-- MySQL
SELECT H.HACKER_ID, H.NAME, SUM(T.SCORE)
FROM HACKERS AS H
    JOIN (SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS SCORE
        FROM SUBMISSIONS
        GROUP BY HACKER_ID, CHALLENGE_ID) AS T
    ON H.HACKER_ID = T.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(T.SCORE) <> 0
ORDER BY SUM(T.SCORE) DESC, H.HACKER_ID
