SELECT W1.ID, P1.AGE, W1.COINS_NEEDED, W1.POWER
FROM WANDS AS W1
    JOIN WANDS_PROPERTY AS P1 ON W1.CODE = P1.CODE AND P1.IS_EVIL = 0
    JOIN (SELECT W.POWER, P.AGE, MIN(W.COINS_NEEDED) AS MIN_PRICE
        FROM WANDS AS W 
            JOIN WANDS_PROPERTY AS P ON W.CODE = P.CODE AND P.IS_EVIL = 0
        GROUP BY W.POWER, P.AGE) AS T ON W1.POWER = T.POWER AND P1.AGE = T.AGE AND W1.COINS_NEEDED = T.MIN_PRICE
ORDER BY W1.POWER DESC, P1.AGE DESC
