SELECT C.COMPANY_CODE, C.FOUNDER, COUNT(DISTINCT LM.LEAD_MANAGER_CODE), COUNT(DISTINCT SM.SENIOR_MANAGER_CODE), COUNT(DISTINCT M.MANAGER_CODE), COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM COMPANY AS C, LEAD_MANAGER AS LM, SENIOR_MANAGER AS SM, MANAGER AS M, EMPLOYEE AS E
WHERE C.COMPANY_CODE = LM.COMPANY_CODE
    AND C.COMPANY_CODE = SM.COMPANY_CODE
    AND C.COMPANY_CODE = M.COMPANY_CODE
    AND C.COMPANY_CODE = E.COMPANY_CODE
GROUP BY C.COMPANY_CODE, C.FOUNDER
ORDER BY C.COMPANY_CODE